package week5LkProvisional;

import java.util.ArrayList;

public class BookingSystem 
{
	////////// Properties //////////
	
	// An arrayList of caravans
	private ArrayList<Caravan> caravans;
	// An arrayList of bookings
	private ArrayList<ProvisionalBooking> bookings;
	
	////////// Constructor //////////
	
	// The constructor will create a new arrayList of caravans and add a new caravan to the list
	public BookingSystem()
	{
		caravans = new ArrayList<Caravan>();
		caravans.add(new Caravan());
	}
	
	
	// This will return an array list that contains Caravan(s) and will accept a string 
	public ArrayList<Caravan> findCaravan(String facility)
	{
		// A new array list is made that will contain Caravan objects
		ArrayList<Caravan> tempCaravans = new ArrayList<Caravan>();
		
		// Looping through the caravan arrayList
		for(int i = 0; i < caravans.size(); i++)
		{	
			// Get the current Caravan object in position i
			Caravan c = caravans.get(i);
			
			// If the Caravan is available
			if(c.isAvailable())
			{
				// Check if the caravan has the string facility
				if(c.hasFacility(facility))
					// If its true add it to the temp arrayList
					tempCaravans.add(c);
			}
		}
		// Return the temp arrayList
		return tempCaravans;
	}
	
	// Confirm a provisional booking which accepts a Caravan and a string id
	public int confirmBooking(Caravan c, String customerId)
	{
		// Create an arrayList of bookings
		bookings = new ArrayList<ProvisionalBooking> ();
		
		// Make a ProvisionalBooking object
		ProvisionalBooking pb = new ProvisionalBooking(c, customerId);
		
		// Add the provisionalBooking to the arrayList
		bookings.add(pb);
		
		// return the autoGenerated booking number
		return pb.getBookingNumber();
	}
	
	// Add a caravan to the caravans array list
	public void addCaravan(Caravan c)
	{
		caravans.add(c);
	}
}
